---
version: "3"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    ports:
      - 8096:8096 #http
      - 8920:8920 #https
      - 7359:7359/udp #server
      - 1900:1900/udp #dlna
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=latest
    volumes:
      - /data/git/docker-compose-jellyfin/config:/config
      - /data/tmp/cache:/cache
      - /data/plex:/media
    restart: unless-stopped
